### ISSUE TITLE
#U15 Cadastro do usuário com erro salvando no banco

### ISSUE THREAD

**Issue by modestoo** [GestorPsi-MES/gestorpsi#15]
Ao tentar efetuar o cadastro de usuário, caso ocorra algum erro (ex. CPF inválido) o sistema salva no banco de dados o usuário e exibe uma mensagem de erro dizendo o contrário.

**Comment by leandrokanis** [comment]
@modestoo , @AlessandroCaetano

**Comment by modestoo** [comment]
ISSUE já está resolvida!
