### ISSUE TITLE
Page Scrolling

### ISSUE THREAD

**Issue by alessandrocaetanob** [GestorPsi-MES/gestorpsi#4]
Scrolling in sign up page works only under Chrome and, if I'm not mistaken, Safari. On Firefox I have to navigate throughout the fields using tab

**Comment by leandrokanis** [comment]
On CSS there is a overflow-y: hidden; for the body.
To fix that, just write overflow-y: visible;

**Comment by leandrokanis** [comment]
CAEP-UnB/gestorpsi#24
