### ISSUE TITLE
#U7 - Numero de identificação de documento

### ISSUE THREAD

**Issue by modestoo** [GestorPsi-MES/gestorpsi#7]
Como um usuário,
Eu quero inserir um número de identificação em registros,
Para acompanhar e identificar cada gráfico.

Responsáveis: @leandrokanis

**Comment by cristianocs** [comment]
As a User,
I want enter a identification number on records,
To keep track and identify each chart.

**Comment by modestoo** [comment]
Par: Alessandro & Augusto
